# Generated by Django 2.2.4 on 2019-08-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='developer_email',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='date_posted',
        ),
    ]
