# Generated by Django 2.2.4 on 2019-08-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='date_posted',
        ),
    ]
