# Generated by Django 2.2.4 on 2019-09-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='material_name',
            new_name='material',
        ),
    ]
