# Generated by Django 2.2.4 on 2019-08-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material_name',
            field=models.CharField(choices=[('Cement', 'Cement'), ('Brick', 'Brick'), ('Sand', 'Sand'), ('Ballast', 'Ballast'), ('Metal rods', 'Metal rods'), ('Roofing tiles', 'Roofing tiles'), ('Plywood', 'Plywood'), ('Timber', 'Timber'), ('Glass', 'Glass')], default='Cement', max_length=20),
        ),
    ]
