# Generated by Django 2.2.4 on 2019-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0002_auto_20190901_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='material',
        ),
        migrations.AddField(
            model_name='requests',
            name='material_name',
            field=models.CharField(choices=[('Cement', 'Cement'), ('Brick', 'Brick'), ('Sand', 'Sand'), ('Ballast', 'Ballast'), ('Metal rods', 'Metal rods'), ('Roofing tiles', 'Roofing tiles')], default='Cement', max_length=20),
        ),
    ]
