# Generated by Django 2.2.4 on 2019-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0003_auto_20190901_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
    ]
