# Generated by Django 2.2.4 on 2019-08-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjenzi_api', '0004_delete_emailrecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
